# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosample', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointofinterest',
            options={'verbose_name': 'Point of interest', 'verbose_name_plural': 'Points of interest'},
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='address',
            field=models.CharField(max_length=255, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='city',
            field=models.CharField(max_length=50, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='zipcode',
            field=models.CharField(max_length=10, verbose_name='zip code'),
        ),
    ]
